### ISSUE TITLE
Building with libtrix?

### ISSUE THREAD

**Issue by JamesLMilner** [anoved/hmstl#10]
Hi there,

This project looks great, thanks for all your hard work. I am new to C and am having some difficulty getting the project to build with the the libtrix dependency. 

```
/usr/bin/ld: cannot find -ltrix
collect2: error: ld returned 1 exit status
make: *** [hmstl] Error 1

```

Do you have any advice for building hmstl from scratch with your libtrix library? I am using Ubuntu if that changes anything!

**Comment by anoved** [comment]
Thanks for the interest. [Here is libtrix](https://github.com/anoved/libtrix)... it should compile with `make` and `make install`. However I am not a C expert either. I would recommend checking out [phstl](https://github.com/anoved/phstl) instead as it is a more recent effort and what I use today for making terrain models from heightmap images.

**Comment by JamesLMilner** [comment]
Thanks @anoved, I've moved to the Python version for now :)

**Comment by ghorn** [comment]
Can this be closed?
