### ISSUE TITLE
heightmap surface is not perfectly watertight

### ISSUE THREAD

**Issue by codehero** [anoved/hmstl#9]
I really like your program but encountered an issue:

The calculation of z coordinates for Vertex 1, 2, 3, 4 can result in differences of 1 ULP based on the pixel vertex location.
So if a point P on the map is V1 for pixel H, but point P on the map is V3 for pixel H2, then Z calculations for point P may differ by 1 ULP.

I believe this is due to rounding introduced in the for loop in avgnonneg().

For my application I rounded z values to 0.001 and fixed the issue for my application.
Similarly you may want to add a z rounding parameter.

**Comment by codehero** [comment]
Another solution would be to only calculate the averages once and cache them.

**Comment by anoved** [comment]
Yep, good catch. In fact I think my whole approach to triangulating the raster was overly complicated in this program. You may be interested in [phstl](https://github.com/anoved/phstl), a Python script I wrote to perform a similar function. It does not try to interpolate "pixel corner" elevations at all.
